package citi.entity;
// Generated 2018-5-28 2:23:42 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "STAFF", schema = "PUBLIC", catalog = "SSDB")
public class Staff implements java.io.Serializable {

	private String soeid;
	private String name;
	private String location;
	private String unit;
	private String team;
	private Boolean isadmin;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Staff() {
	}

	public Staff(String soeid) {
		this.soeid = soeid;
	}

	public Staff(String soeid, String name, String location, String unit, String team, Boolean isadmin,
			Set<Orders> orderses) {
		this.soeid = soeid;
		this.name = name;
		this.location = location;
		this.unit = unit;
		this.team = team;
		this.isadmin = isadmin;
		this.orderses = orderses;
	}

	@Id

	@Column(name = "SOEID", unique = true, nullable = false, length = 15)
	public String getSoeid() {
		return this.soeid;
	}

	public void setSoeid(String soeid) {
		this.soeid = soeid;
	}

	@Column(name = "NAME", length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LOCATION", length = 25)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "UNIT", length = 25)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "TEAM", length = 25)
	public String getTeam() {
		return this.team;
	}

	public void setTeam(String team) {
		this.team = team;
	}

	@Column(name = "ISADMIN")
	public Boolean getIsadmin() {
		return this.isadmin;
	}

	public void setIsadmin(Boolean isadmin) {
		this.isadmin = isadmin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
